services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:1.91.3
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Configuration Neon DB
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: neondb
      - key: DB_POSTGRESDB_HOST
        value: ep-still-flower-ab4c8bq3-pooler.eu-west-2.aws.neon.tech
      - key: DB_POSTGRESDB_USER
        value: neondb_owner
      - key: DB_POSTGRESDB_PASSWORD
        value: npg_AXL2pOPTV1mQ
      - key: DB_POSTGRESDB_PORT
        value: "5432"

      # 🔐 Contourne l'erreur SSL
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"

      # ✅ Webhook + timezone
      - key: WEBHOOK_URL
        value: https://n8n-service.onrender.com
      - key: GENERIC_TIMEZONE
        value: Europe/Paris

      # 🔧 Pour corriger le warning des permissions
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
