services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:1.91.3
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Configuration de la base PostgreSQL Neon
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: n8n-db-fresh
      - key: DB_POSTGRESDB_HOST
        value: ep-polished-night-a8fst5by-pooler.eastus2.azure.neon.tech
      - key: DB_POSTGRESDB_USER
        value: n8n-db-fresh_owner
      - key: DB_POSTGRESDB_PASSWORD
        value: npg_6XtQrwi8FnoE
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"

      # Configuration n8n
      - key: WEBHOOK_URL
        value: https://n8n-service.onrender.com
      - key: GENERIC_TIMEZONE
        value: Europe/Paris
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
