services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:1.91.3
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Config base Neon
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: neondb
      - key: DB_POSTGRESDB_HOST
        value: ep-still-flower-ab4c8bq3-pooler.eu-west-2.aws.neon.tech
      - key: DB_POSTGRESDB_USER
        value: neondb_owner
      - key: DB_POSTGRESDB_PASSWORD
        value: npg_AXL2pOPTV1mQ
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"     # 👈 la clé magique

      # Info service
      - key: WEBHOOK_URL
        value: https://n8n-service.onrender.com
      - key: GENERIC_TIMEZONE
        value: Europe/Paris
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
